services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    networks:
      - app-network
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    depends_on:
      - postgres
    ports:
      - 5000:8080
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
  frontend:
    container_name: frontend
    build:
      context: src/front
      dockerfile: Dockerfile
    image: frontend:latest
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - app-network
networks:
  app-network:
